### ISSUE TITLE
JEI is broken for enrichment

### ISSUE THREAD

**Issue by v1993** [Team-AbCiv/IC2Tweaker#5]
I have the following script that allows to enrich water/distilled water into Ink from Mystcraft:

```
mods.ic2.Canner.addEnrichRecipe(<liquid:myst.ink.black> * 1000, <liquid:water> * 1000, <ore:dyeBlack> * 2);
mods.ic2.Canner.addEnrichRecipe(<liquid:myst.ink.black> * 2000, <liquid:ic2distilled_water> * 2000, <ore:dyeBlack>);
```

The problem is that in JEI item slot shows only vanilla black dye (ink sack) and doesn't indicate that two are needed with subscript, making it confusing. It still functions properly, however, accepting all black dyes and requiring two of them, only JEI is broken.

**Comment by 3TUSK** [comment]
Reproduced locally and "fixed".

![image](https://user-images.githubusercontent.com/9113033/199168210-df5ef2f9-442a-46ca-bd32-0ad3c47a75d1.png)

The reason I put quotes on "fixed" is that, there are more corner cases that still suffer from this issue, but those corner cases are out of my control. For example, the screenshot you see here is produced by the following ZenScript code:

```zenscript
// Notice that I use the OR operator to allow both dustIron or dustGold to work, 
// but due to how IC2 implements its JEI integration, the dustGold option is still not shown properly.
// Only the 3 * dustIron is shown.
Canner.addEnrichRecipe(<liquid:lava> * 3000, <liquid:water> * 1000, <ore:dustIron> * 3 | <ore:dustGold> * 5);
```

**Comment by 3TUSK** [comment]
https://www.curseforge.com/minecraft/mc-mods/ic2-tweaker/files/4083913

New version has been released. Please try and let me know if anything goes wrong.
