### ISSUE TITLE
IC2 blast furnace doesnt display amount when oreDictionary is used

### ISSUE THREAD

**Issue by seras42** [Team-AbCiv/IC2Tweaker#6]
import mods.ic2.BlastFurnace;
import crafttweaker.item.IIngredient;
import crafttweaker.item.IItemStack;
import crafttweaker.oredict.IOreDictEntry;
enableDebug();

var CopperOre = [
ore:oreCopperNormal,
ore:oreCopperPoor,
ore:oreRichCopper,
ore:oreCopperSmall
] as IIngredient[];

function BlastFurnace(inputOre as IIngredient[], output as IItemStack) {
val numbers = [
3,5,2,7
] as int[];

for i, ore in inputOre {
   mods.ic2.BlastFurnace.addRecipe([output,<ic2:misc_resource:5>], ore * numbers[i], 1, 2500);
    }

}
BlastFurnace(CopperOre,tfc:metal/ingot/copper);

For some reason JEI doesn't show the amount of ore needed to craft the ingot. Before that when i did not use ore dictionary it worked, then i changed it to ore dictionary to make the code shorter and now it doesn't show it even tough the recipe works correctly.

Minecraft version 1.12.2
Forge 14.23.5.2859
Craft Tweaker2 4.1.20.675
IC2 Tweaker 2.0

**Comment by seras42** [comment]
![scer](https://user-images.githubusercontent.com/109229384/179301434-a3b096c3-c7a2-4a24-9ae3-7f3debe02af9.png)
For this ore it should show 7 ores needed to craft one ingot. If for example i edit the recipes trough blast_furnace.ini in IC2 config folder and use ore Dictionary it works. But if i use craftTweaker scrip and use ore dictionary it doesnt work.

**Comment by seras42** [comment]
I added the recipes trough blastfurnace.ini in the ic2 config file and trough there it works so i guess i resolved the issue.

**Comment by 3TUSK** [comment]
Probably a duplicate of #5. See there for more details.

Update: reproduced locally. Confirmed as a duplicate.

**Comment by 3TUSK** [comment]
Duplicate of #5
