### ISSUE TITLE
mods.ic2.SemiFluidGenerator.addFluid doesnt work

### ISSUE THREAD

**Issue by seras42** [Team-AbCiv/IC2Tweaker#7]
mods.ic2.SemiFluidGenerator.addFluid doesnt work and gives an error even when example code is used. I talked with crafttweaker creator and he said its something to do with this mod not being updated.
The code example mods.ic2.SemiFluidGenerator.addFluid(<liquid:water>, 2333.0D);

[INITIALIZATION][CLIENT][ERROR] [crafttweaker]: Error executing {[0:crafttweaker]: IC2/semiFluidGenerator.zs}: ic2.api.recipe.ISemiFluidFuelManager.addFluid(Ljava/lang/String;ID)V
java.lang.NoSuchMethodError: ic2.api.recipe.ISemiFluidFuelManager.addFluid(Ljava/lang/String;ID)V

Minecraft version 1.12
Newest version of IC2

**Comment by 3TUSK** [comment]
Just a reminder, "Newest version of IC2" is not a version number. You have to give the exact version number.

Solution for now is to downgrade IC2 version to 2.8.215. I believe I have "fixed" the same issue just now; whoever you talked to is correct about my mod being outdated, but the problem also involves API breaking change on IC2 side which is another headache.

**Comment by seras42** [comment]
Hello, thank you for the reply, the IC2 version is "industrialcraft-2-2.8.222-ex112.jar"
https://www.curseforge.com/minecraft/mc-mods/industrial-craft/files/3838713
my bad for not providing the exact version, i don't know what i was thinking back then when i submitted the issue.

**Comment by 3TUSK** [comment]
https://www.curseforge.com/minecraft/mc-mods/ic2-tweaker/files/4083913

New version has been released. Please try and let me know if anything goes wrong.
