### ISSUE TITLE
[support] maxDamage

### ISSUE THREAD

**Issue by Romz24** [Team-AbCiv/IC2Tweaker#8]
I'm trying to use **maxDamage** to change the max durability of an item but it doesn't work. Can you please add a feature that will make it possible to change the durability of items from the ic2 mod?

```
var rotor_carbon = <ic2:rotor_carbon>;

print("rotor_carbon: " ~ rotor_carbon.maxDamage);
rotor_carbon.maxDamage = 1000;
print("rotor_carbon: " ~ rotor_carbon.maxDamage);
```

```
[INITIALIZATION][CLIENT][INFO] rotor_carbon: 604800
[INITIALIZATION][CLIENT][INFO] Setting max damage of  Carbon Rotor to 1000
[INITIALIZATION][CLIENT][INFO] rotor_carbon: 604800
```

**Comment by 3TUSK** [comment]
All (wind) rotors in IC2 have custom implementation for max damage.

I will see what I can do about it.

**Comment by Romz24** [comment]
It seems to be a problem with the ic2 mod, even if you force the item name to change, it changes back to the original. All changes from scripts (CraftTweaker) are simply discarded.

**Comment by 3TUSK** [comment]
> It seems to be a problem with the ic2 mod, even if you force the item name to change, it changes back to the original. All changes from scripts (CraftTweaker) are simply discarded.

Yes, that is because IC2 decides to store rotor damage in NBT. So it has to have custom implementation for damage-related things, but they somehow missed `Item.setMaxDamage`.

*Edit: … or it is intentional. It seems that IC2 doesn't anticipate the possibility of changing max durability of rotors.*

*Edit II: regarding display name. Mind you sharing your script? Typically, you'd like to change the language file in order to change the display name of a certain item.*

Do you mind having something like this:

```zenscript
print("rotor_carbon: " ~ rotor_carbon.ic2MaxDamage); // In theory this would be just alias of maxDamage
rotor_carbon.ic2MaxDamage = 1000;
print("rotor_carbon: " ~ rotor_carbon.maxDamage);
```

?

**Comment by 3TUSK** [comment]
<img width="528" alt="Screen Shot 2022-11-01 at 5 56 39 PM" src="https://user-images.githubusercontent.com/9113033/199369656-5f0830ae-b269-49a7-b0ce-2e75442e0141.png">

Update: the proposed solution in action.

**Comment by Romz24** [comment]
> regarding display name. Mind you sharing your script?

```
<minecraft:diamond>.displayName = "[NEW] Rename minecraft item";
<ic2:dust:31>.displayName = "[NEW] Rename IC2 item";
```

Old:
![image](https://user-images.githubusercontent.com/2458113/199387052-c2403cd4-719f-460d-b8a2-3d045f3797cf.png)

New:
![image](https://user-images.githubusercontent.com/2458113/199387085-476d4706-e5b5-427e-b81e-784861198c1a.png)

**Comment by Romz24** [comment]
> Do you mind having something like this

Why not? Looks pretty comfortable.

**Comment by 3TUSK** [comment]
Tried on my own.

CraftTweaker uses wrong translation key when overriding the display name. This is out of my control. The correct translation key for `<item:ic2:dust:31>` should be `ic2.dust.ender_pearl` but CraftTweaker uses `ic2.dust.ender_pearl.name`.

I can only suggest to use a resourcepack to override this.

------

Regarding to the main topic of this ticket. I will go with `ic2Damage` and `ic2MaxDamage` then. Documentation will come later.

**Comment by Romz24** [comment]
@3TUSK 

Can you do something similar so that you can conveniently change the charge level and energy of items through scripts? At the moment, all this data is recorded in NBT, and if this is the charge level, in addition to NBT, we also need to edit the damage of the item so that it is displayed visually (for example, if it is a drill, or an energy crystal).

![image](https://user-images.githubusercontent.com/2458113/199403922-0b48b5cb-0e71-4f7d-b157-30dbf59b2297.png)

I think it should work like this:
```
<myic2item>.ic2Charge = 1000000; // set item charge (nbt + damage)
print("item: " ~ <myic2item>.ic2Charge); // return item charge
print("item: " ~ <myic2item>.ic2MaxCharge); // return item max charge
```
```
<myic2item>.ic2Enegy = 4000000; // set item energy (ntb)
print("item: " ~ <myic2item>.ic2Enegy); // return item energy
print("item: " ~ <myic2item>.ic2MaxEnegy); // return item max energy
```

**Comment by 3TUSK** [comment]
Sure. For easier management I have created GH-10 to track this feature.

**Comment by 3TUSK** [comment]
https://www.curseforge.com/minecraft/mc-mods/ic2-tweaker/files/4083913

New version has been released. Please try and let me know if anything goes wrong.
